#!/usr/bin/env python3
"""Generate DAG.md from design dependency declarations.

Scans unified-design/designs/*.yaml, extracts depends_on and bridges,
and regenerates DAG.md with the current dependency graph.
Handles multi-document YAML files gracefully.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DESIGNS_DIR = REPO_ROOT / "designs"
DAG_PATH = REPO_ROOT / "DAG.md"


def load_design(path: Path) -> dict[str, Any] | None:
    """Load a design YAML, handling multi-document streams."""
    text = path.read_text(encoding="utf-8")
    try:
        # Try single document first
        data = yaml.safe_load(text)
        if isinstance(data, dict):
            return data
    except yaml.YAMLError:
        pass

    # Try multi-document stream (take first valid document)
    try:
        for doc in yaml.safe_load_all(text):
            if isinstance(doc, dict):
                return doc
    except yaml.YAMLError:
        pass

    print(f"[WARN] Failed to parse design: {path}")
    return None


def load_designs() -> dict[str, dict[str, Any]]:
    designs = {}
    for path in sorted(DESIGNS_DIR.glob("*.yaml")):
        data = load_design(path)
        if not data:
            continue
        name = data.get("name", path.stem)
        # Normalize .design suffix for consistency
        if name.endswith(".design"):
            name = name[:-7]
        designs[name] = {
            "path": path,
            "data": data,
            "depends_on": data.get("depends_on", []),
            "bridges": data.get("bridges", []),
            "status": data.get("status", "unknown"),
            "layer": data.get("layer", "unknown"),
        }
    return designs


def generate_dag_md(designs: dict[str, dict[str, Any]]) -> str:
    lines = []
    lines.append("# Design Dependency Graph")
    lines.append("")
    lines.append("Auto-generated by `scripts/generate_dag.py`. Do not edit manually.")
    lines.append("")
    lines.append("## Designs")
    lines.append("")

    for name, meta in sorted(designs.items()):
        status = meta["status"]
        layer = meta["layer"]
        depends = meta["depends_on"]
        bridges = meta["bridges"]

        lines.append(f"### {name}")
        lines.append(f"- **Status**: {status}")
        lines.append(f"- **Layer**: {layer}")
        if depends:
            lines.append(f"- **Depends on**: {', '.join(depends)}")
        if bridges:
            bridge_targets = [f"{b.get('target', '?')} ({b.get('role', '?')})" for b in bridges]
            lines.append(f"- **Bridges**: {', '.join(bridge_targets)}")
        lines.append("")

    lines.append("## Dependency Matrix")
    lines.append("")
    lines.append("| Design | Depends On | Bridges |")
    lines.append("|--------|------------|---------|")
    for name, meta in sorted(designs.items()):
        depends = ", ".join(meta["depends_on"]) if meta["depends_on"] else "-"
        bridges = ", ".join(b.get("target", "?") for b in meta["bridges"]) if meta["bridges"] else "-"
        lines.append(f"| {name} | {depends} | {bridges} |")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    designs = load_designs()
    dag_md = generate_dag_md(designs)
    DAG_PATH.write_text(dag_md, encoding="utf-8")
    print(f"[OK] Generated {DAG_PATH} ({len(designs)} designs)")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
