#!/usr/bin/env python3
"""
generate_reusable_workflow.py  Gnrateur de workflow rutilisable RSS-v2.

Orchestr par :
- SABRE : planification et rendering
- RIDDLER : injection auto sur repos non-conformes
- SELINA : propagation cross-repo
- ALFRED : validation des PRs

IntentHash: 0xGENERATE_REUSABLE_WORKFLOW_20260705
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def generate_workflow_yaml() -> str:
    """Gnre le contenu YAML du workflow rutilisable."""
    return """# GitHub Actions Reusable Workflow - RSS-v2
# Generated by SABRE + RIDDLER pipeline
# IntentHash: 0xRSS_V2_REUSABLE_WORKFLOW_20260705

name: "RSS-v2 Reusable Checks"

on:
  workflow_call:
    inputs:
      repo-path:
        description: 'Path to repository to check'
        required: false
        default: '.'
      check-profile:
        description: 'Validate RSS profile compliance'
        required: false
        default: 'true'
      check-security:
        description: 'Run security scans'
        required: false
        default: 'false'

jobs:
  rss-lint:
    name: RSS-v2 Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Run RSS-v2 linter
        run: |
          python scripts/rss_lint.py \\
            --repo "${{ inputs.repo-path }}" \\
            --all-checks \\
            --check-profile "${{ inputs.check-profile }}"

  branch-check:
    name: Branch Naming Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check branch name
        run: |
          BRANCH="${{ github.head_ref }}"
          VALID_PATTERN="^(feature|fix|refactor|docs|chore|adr|meta|test|wip)/.+\\|^(main|develop)\\|^adr-.+"
          if ! echo "${BRANCH}" | grep -qE "${VALID_PATTERN}"; then
            echo "::error::Branch '${BRANCH}' does not follow RSS convention."
            exit 1
          fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    if: ${{ inputs.check-security == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit --format=json || true
      - name: Run Trivy SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'spdx-json'
          output: 'sbom.spdx.json'
          severity: 'CRITICAL,HIGH'

outputs:
  conformity-score:
    description: 'Percentage of checks passed'
    value: ${{ steps.rss-lint.outcome == 'success' && '100' || '0' }}
"""


def main():
    parser = argparse.ArgumentParser(description="Generate RSS-v2 Reusable Workflow")
    parser.add_argument("--output", type=str, default=".github/workflows/rss-v2-reusable.yml",
                        help="Output file path")
    parser.add_argument("--dry-run", action="store_true", help="Print YAML without writing")
    parser.add_argument("--wal", action="store_true", help="Write WAL entry")
    args = parser.parse_args()

    yaml_content = generate_workflow_yaml()

    if args.dry_run:
        print(yaml_content)
        return 0

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(yaml_content, encoding="utf-8")
    print(f"Workflow generated: {output_path}")

    if args.wal:
        wal_path = Path("wal/GENERATE_REUSABLE_WORKFLOW_WAL.jsonl")
        wal_path.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "event": "GENERATE_REUSABLE_WORKFLOW",
            "action": "generate",
            "output": str(output_path),
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "intent_hash": "0xGENERATE_REUSABLE_WORKFLOW_20260705",
        }
        wal_path.write_text(json.dumps(entry, ensure_ascii=False) + "\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())